# Generated by Django 6.0.5 on 2026-05-13 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nif', models.CharField(max_length=50, unique=True)),
                ('type_contribuable', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Impot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_impot', models.CharField(choices=[('revenu', 'Impôt sur le revenu'), ('societe', 'Impôt sur les sociétés'), ('tva', 'TVA'), ('foncier', 'Impôt foncier'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impots', to='impots.contribuable')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('montant_declare', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=20)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='impots.contribuable')),
                ('impot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='impots.impot')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('impot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='impots.impot')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motif', models.TextField()),
                ('date_application', models.DateTimeField(auto_now_add=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('impot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='impots.impot')),
            ],
            options={
                'ordering': ['-date_application'],
            },
        ),
    ]
