# Generated by Django 6.0.5 on 2026-05-22 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impot',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('paiement', 'Paiement'), ('declaration', 'Déclaration'), ('penalite', 'Pénalité'), ('rappel', 'Rappel')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='impots.contribuable')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire')], default='gestionnaire', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
